### ISSUE TITLE
Interval has incorrect value or format (JS API)

### ISSUE THREAD

**Issue by boondigga** [GIScience/openrouteservice-js#26]
When trying to fetch isochrones using the Javascript API:

     const geojson = await Isochrones.calculate({
       locations: [[lon, lat]],
       profile: profile,
       range: [900],
       range_type: 'time',
       area_units: 'm',
       units: 'm',
       interval: [300]
     })

I get the following error message:

`"error":{"code":3002,"message":"Parameter \'interval\' has incorrect value or format`
According to the `OrsIsochroneSchema.js`, it `can be a list of multiple ranges, e.g. [600, 1200, 1400] or a single value list`. 

Neither [300] nor [300, 600, 900] are working.

**Comment by amoncaldas** [comment]
Hey boondigga,
We decided to remove the lib object validation. Now only the API validation applies. So, it must be solved.
