### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by karelbyte** [GIScience/openrouteservice-js#27]
Hi, thanks for this great tool, I have the following query, on the interactive map I have this test route
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=40.4442%2C-3.8037%3B40.4412%2C-3.7914#map=16/40.4414/-3.7980
and the system gives me the relevant data and routes, all ok, now when I want to pass the range of [40.4442, -3.8037], [40.4412, -3.7914] to the api
`Directions.calculate ({
         coordinates: [[40.4442, -3.8037], [40.4412, -3.7914]],
         profile: 'driving-car',
         extra_info: ['waytype', 'steepness'],
         format: 'json'
       })
         .then (function (json) {
           console.log (JSON.stringify (json))
         })
         .catch (function (err) {
           const str = 'An error occured:' + err
           console.log (str)
         })`

Ireturn the error **An error occured: Error: Not Found**

 please some help to fix it, thanks

**Comment by rabidllama** [comment]
hi @karelbyte 
from what I can see, that is the osrm engine and not openrouteservice, so any queries about that you would need to get in contact with them.
