### ISSUE TITLE
Support to Optimization Api 

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice-js#30]
hi

I was wondering why the optimization API was not included, in python bindings it is present.

would you accept a PR having this?
or is it not present for other technical or commercial reasons?

best regards
Stefano

**Comment by nilsnolde** [comment]
Sure, definitely accepting PRs for that:) Might take a little while until someone can properly review it right now, but that would be really helpful!

**Comment by stefanocudini** [comment]
ah ok I just wanted to understand if it was a choice or because the optimization api arrived after others in ors.
