### ISSUE TITLE
URL for Matrix Service is wrong

### ISSUE THREAD

**Issue by silika** [GIScience/openrouteservice-js#39]
When we use Matrix service 
`Matrix.calculate({
  locations: [[8.690958, 49.404662], [8.687868, 49.390139], [8.687868, 49.390133]],
  profile: "driving-car",
  sources: ['all'],
  destinations: ['all']
})`
Browser send request to `https://api.openrouteservice.org/matrix/v2/matrix/driving-car/json`
Word 'matrix' uses twice in URL

**Comment by amoncaldas** [comment]
Hey @silika 
I could not reproduce this issue.
There is an automated test that run requests using all the endpoints, including matrix and it is working. All the tests are passing, including the using matrix. You can check the test here: https://github.com/GIScience/openrouteservice-js/blob/master/spec/OrsMatrixSpec.js#L22

Additionally, only to make sure, I have run it locally on debug mode and the URL used to run the request is correct. You can check this in the screenshot below. There is probably some bug in your code when using the library. Maybe you are passing wrong parameters to it?
![matrix-url](https://user-images.githubusercontent.com/13475791/146593536-58e1ec0e-b592-4d63-9df8-cc3fedfe6d4a.png)
