### ISSUE TITLE
Allow to use self-hosted ORS

### ISSUE THREAD

**Issue by gabsoftware** [GIScience/openrouteservice-js#67]
Maybe I'm missing something, but I think this API can't be used with self-hosted instances of OpenRouteService. Would it be possible to add support for this?

**Comment by TheGreatRefrigerator** [comment]
This is probably just not documented.
You should be able to pass a `host` argument, when initializing the client e.g.:
```
import Openrouteservice from 'openrouteservice-js'
let orsDirections = new Openrouteservice.Directions({ api_key: "XYZ", host: "localhost:8082/ors"});
// ...
```
I'm not 100% sure it works, but will try it out and get back to you

**Comment by TheGreatRefrigerator** [comment]
This was documented in d2752b55007400baa2a030ca9dd7feb422d93d6a
