### ISSUE TITLE
[Bug] Missing twitter tweet link from website

### ISSUE THREAD

**Issue by Ghat0tkach** [GIScience/openrouteservice-js#74]
The twitter tweet link isnt visible on the website , it must be broken .
![image](https://github.com/GIScience/openrouteservice-js/assets/59855919/7b2fd81f-e60c-497b-94ff-1cdda6ba73de)

**Comment by TheGreatRefrigerator** [comment]
This is a problem with one of the WordPress Plugins of our website (nothing to do with the js package, but thx for reporting)
This is due to the recent changes that Twitter did to its APIs. The WordPress plugins have a hard time catching up on them.
Might be solved soon

**Comment by TheGreatRefrigerator** [comment]
This is resolved. However, with the current free tier of the twitter plugin, retweets won't be shown anymore.
